PocketMine-MP: pocketmine\inventory\transaction\SlotChangeActionBuilder Class Reference
pocketmine\inventory\transaction\SlotChangeActionBuilder Class Reference
Public Member Functions
__construct (private InventoryWindow $inventoryWindow)
addItem (Item ... $slots)
all (Item $item)
canAddItem (Item $item)
clear (int $index)
clearAll ()
contains (Item $item)
first (Item $item, bool $exact=false)
firstEmpty ()
generateActions ()
getAddableItemQuantity (Item $item)
getContents (bool $includeEmpty=false)
getInventoryWindow ()
getItem (int $index)
getListeners ()
getMatchingItemCount (int $slot, Item $test, bool $checkTags)
getMaxStackSize ()
getSize ()
getSlotValidators ()
getViewers ()
isSlotEmpty (int $index)
onClose (InventoryWindow $window)
onOpen (InventoryWindow $window)
remove (Item $item)
removeAllWindows ()
removeItem (Item ... $slots)
setContents (array $items)
setItem (int $index, Item $item)
setMaxStackSize (int $size)
slotExists (int $slot)
swap (int $slot1, int $slot2)
Public Attributes
const MAX_STACK = 64
Protected Member Functions
internalSetContents (array $items)
internalSetItem (int $index, Item $item)
onContentChange (array $itemsBefore)
onSlotChange (int $index, Item $before)
Protected Attributes
ObjectSet $listeners
int $maxStackSize = Inventory::MAX_STACK
ObjectSet $validators
Detailed Description
This class facilitates generating SlotChangeActions to build an inventory transaction. It wraps around the inventory you want to modify under transaction, and generates a diff of changes. This allows you to use the normal Inventory API methods like addItem() and so on to build a transaction, without modifying the original inventory.
Definition at line 39 of file SlotChangeActionBuilder.php.
Constructor & Destructor Documentation
__construct()
pocketmine\inventory\transaction\SlotChangeActionBuilder::__construct (private InventoryWindow $inventoryWindow)
Definition at line 47 of file SlotChangeActionBuilder.php.
Member Function Documentation
addItem()
pocketmine\inventory\BaseInventory::addItem (Item ... $slots) inherited
Stores the given Items in the inventory. This will add to any non-full existing stacks first, and then put the remaining items in empty slots if there are any available.
Returns an array of items which could not fit in the inventory.
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 184 of file BaseInventory.php.
all()
pocketmine\inventory\BaseInventory::all (Item $item) inherited
Returns all matching items in the inventory, irrespective of stack size. The returned array is indexed by slot number.
If the input item has specific NBT, only items with the same type and NBT will match. Otherwise, only the item type is checked.
Returns
Item[] @phpstan-return array<int, Item>
Implements pocketmine\inventory\Inventory.
Definition at line 122 of file BaseInventory.php.
canAddItem()
pocketmine\inventory\BaseInventory::canAddItem (Item $item) inherited
Checks if a given Item can be added to the inventory
Implements pocketmine\inventory\Inventory.
Definition at line 158 of file BaseInventory.php.
clear()
pocketmine\inventory\BaseInventory::clear (int $index) inherited
Will clear a specific slot
Implements pocketmine\inventory\Inventory.
Definition at line 298 of file BaseInventory.php.
Referenced by pocketmine\inventory\transaction\SlotChangeActionBuilder\internalSetContents().
clearAll()
pocketmine\inventory\BaseInventory::clearAll () inherited
Clears all the slots
Implements pocketmine\inventory\Inventory.
Definition at line 302 of file BaseInventory.php.
contains()
pocketmine\inventory\BaseInventory::contains (Item $item) inherited
Returns whether the total amount of matching items is at least the stack size of the given item. Multiple stacks of the same item are added together.
If the input item has specific NBT, only items with the same type and NBT will match. Otherwise, only the item type is checked.
Implements pocketmine\inventory\Inventory.
Definition at line 106 of file BaseInventory.php.
first()
pocketmine\inventory\BaseInventory::first (Item $item, bool $exact = false) inherited
Returns the first slot number containing a matching item with a stack size greater than or equal to the input item.
If the input item has specific NBT, or if $exact is true, only items with the same type and NBT will match. Otherwise, only the item type is checked.
Implements pocketmine\inventory\Inventory.
Definition at line 134 of file BaseInventory.php.
firstEmpty()
pocketmine\inventory\BaseInventory::firstEmpty () inherited
Returns the first empty slot, or -1 if not found
Implements pocketmine\inventory\Inventory.
Definition at line 148 of file BaseInventory.php.
generateActions()
pocketmine\inventory\transaction\SlotChangeActionBuilder::generateActions ()
Returns
SlotChangeAction[]
Definition at line 112 of file SlotChangeActionBuilder.php.
getAddableItemQuantity()
pocketmine\inventory\BaseInventory::getAddableItemQuantity (Item $item) inherited
Returns how many items from the given itemstack can be added to this inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 162 of file BaseInventory.php.
getContents()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getContents (bool $includeEmpty = false)
Returns an array of all the itemstacks in the inventory, indexed by their slot number. Empty slots are not included unless includeEmpty is true.
Returns
Item[] @phpstan-return array<int, Item>
Implements pocketmine\inventory\Inventory.
Definition at line 82 of file SlotChangeActionBuilder.php.
getInventoryWindow()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getInventoryWindow ()
Definition at line 54 of file SlotChangeActionBuilder.php.
getItem()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getItem (int $index)
Returns the item in the specified slot.
Implements pocketmine\inventory\Inventory.
Definition at line 78 of file SlotChangeActionBuilder.php.
getListeners()
pocketmine\inventory\BaseInventory::getListeners () inherited
Returns
InventoryListener[]|ObjectSet @phpstan-return ObjectSet<InventoryListener>
Implements pocketmine\inventory\Inventory.
Definition at line 333 of file BaseInventory.php.
getMatchingItemCount()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getMatchingItemCount (int $slot, Item $test, bool $checkTags)
Returns the number of items in the inventory that match the given item.
Parameters
bool $checkTags If true, the NBT of the items will also be checked and must be the same to be counted.
Implements pocketmine\inventory\Inventory.
Definition at line 96 of file SlotChangeActionBuilder.php.
getMaxStackSize()
pocketmine\inventory\BaseInventory::getMaxStackSize () inherited
Returns the maximum stack size for items in this inventory. Individual item types (such as armor or tools) may have a smaller maximum stack size.
Implements pocketmine\inventory\Inventory.
Definition at line 55 of file BaseInventory.php.
getSize()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getSize ()
Returns the number of slots in the inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 74 of file SlotChangeActionBuilder.php.
getSlotValidators()
pocketmine\inventory\BaseInventory::getSlotValidators () inherited
Returns a set of validators that will be used to determine whether an item can be placed in a particular slot. All validators need to return null for the transaction to be allowed. If one of the validators returns an exception, the transaction will be cancelled.
There is no guarantee that the validators will be called in any particular order.
@phpstan-return SlotValidators
Implements pocketmine\inventory\SlotValidatedInventory.
Definition at line 337 of file BaseInventory.php.
getViewers()
pocketmine\inventory\transaction\SlotChangeActionBuilder::getViewers ()
Gets all the Players viewing the inventory Players will view their inventory at all times, even when not open.
Returns
Player[]
Implements pocketmine\inventory\Inventory.
Definition at line 126 of file SlotChangeActionBuilder.php.
internalSetContents()
pocketmine\inventory\transaction\SlotChangeActionBuilder::internalSetContents (array $items) protected
Parameters
Item[] $items @phpstan-param array<int, Item> $items
Reimplemented from pocketmine\inventory\BaseInventory.
Definition at line 58 of file SlotChangeActionBuilder.php.
References pocketmine\inventory\BaseInventory\clear(), and pocketmine\inventory\BaseInventory\setItem().
internalSetItem()
pocketmine\inventory\transaction\SlotChangeActionBuilder::internalSetItem (int $index, Item $item) protected
Reimplemented from pocketmine\inventory\BaseInventory.
Definition at line 68 of file SlotChangeActionBuilder.php.
isSlotEmpty()
pocketmine\inventory\transaction\SlotChangeActionBuilder::isSlotEmpty (int $index)
Returns whether the given slot is empty.
Implements pocketmine\inventory\Inventory.
Definition at line 104 of file SlotChangeActionBuilder.php.
onClose()
pocketmine\inventory\transaction\SlotChangeActionBuilder::onClose (InventoryWindow $window)
Implements pocketmine\inventory\Inventory.
Definition at line 138 of file SlotChangeActionBuilder.php.
onContentChange()
pocketmine\inventory\BaseInventory::onContentChange (array $itemsBefore) protected inherited
Parameters
Item[] $itemsBefore @phpstan-param array<int, Item> $itemsBefore
Definition at line 323 of file BaseInventory.php.
onOpen()
pocketmine\inventory\transaction\SlotChangeActionBuilder::onOpen (InventoryWindow $window)
Called when a player opens this inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 134 of file SlotChangeActionBuilder.php.
onSlotChange()
pocketmine\inventory\BaseInventory::onSlotChange (int $index, Item $before) protected inherited
Definition at line 313 of file BaseInventory.php.
remove()
pocketmine\inventory\BaseInventory::remove (Item $item) inherited
Clears all slots containing items equivalent to the given item.
If the input item has specific NBT, only items with the same type and NBT will match. Otherwise, only the item type is checked.
Implements pocketmine\inventory\Inventory.
Definition at line 252 of file BaseInventory.php.
removeAllWindows()
pocketmine\inventory\transaction\SlotChangeActionBuilder::removeAllWindows ()
Tells all Players viewing this inventory to stop viewing it and discard associated windows.
Implements pocketmine\inventory\Inventory.
Definition at line 130 of file SlotChangeActionBuilder.php.
removeItem()
pocketmine\inventory\BaseInventory::removeItem (Item ... $slots) inherited
Removes items from the inventory in the amounts specified by the given itemstacks. Returns an array of items that couldn't be removed.
If the input item has specific NBT, only items with the same type and NBT will match. Otherwise, only the item type is checked.
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 262 of file BaseInventory.php.
setContents()
pocketmine\inventory\BaseInventory::setContents (array $items) inherited
Parameters
Item[] $items @phpstan-param array<int, Item> $items
Implements pocketmine\inventory\Inventory.
Definition at line 88 of file BaseInventory.php.
setItem()
pocketmine\inventory\BaseInventory::setItem (int $index, Item $item) inherited
Puts an Item in a slot.
Implements pocketmine\inventory\Inventory.
Reimplemented in pocketmine\crafting\CraftingGrid.
Definition at line 65 of file BaseInventory.php.
Referenced by pocketmine\inventory\transaction\SlotChangeActionBuilder\internalSetContents().
setMaxStackSize()
pocketmine\inventory\BaseInventory::setMaxStackSize (int $size) inherited
Sets the maximum stack size for items in this inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 59 of file BaseInventory.php.
slotExists()
pocketmine\inventory\BaseInventory::slotExists (int $slot) inherited
Returns whether the specified slot exists in the inventory.
Implements pocketmine\inventory\Inventory.
Definition at line 329 of file BaseInventory.php.
swap()
pocketmine\inventory\BaseInventory::swap (int $slot1, int $slot2) inherited
Swaps the specified slots.
Implements pocketmine\inventory\Inventory.
Definition at line 306 of file BaseInventory.php.
Member Data Documentation
$listeners
ObjectSet pocketmine\inventory\BaseInventory::$listeners protected inherited
Definition at line 46 of file BaseInventory.php.
$maxStackSize
int pocketmine\inventory\BaseInventory::$maxStackSize = Inventory::MAX_STACK protected inherited
Definition at line 41 of file BaseInventory.php.
$validators
ObjectSet pocketmine\inventory\BaseInventory::$validators protected inherited
@phpstan-var SlotValidators
Definition at line 48 of file BaseInventory.php.
MAX_STACK
const pocketmine\inventory\Inventory::MAX_STACK = 64 inherited
Definition at line 35 of file Inventory.php.
The documentation for this class was generated from the following file:
SlotChangeActionBuilder.php