PocketMine-MP: pocketmine\command\defaults\VanillaCommand Class Reference
pocketmine\command\defaults\VanillaCommand Class Reference
Public Member Functions
execute (CommandSender $sender, string $commandLabel, array $args)
getDescription ()
getId ()
getName ()
getNamespace ()
getPermissionMessage ()
getPermissions ()
getUsage ()
setDescription (Translatable|string $description)
setPermission (?string $permission)
setPermissionMessage (Translatable|string $permissionMessage)
setPermissions (array $permissions)
setUsage (Translatable|string|null $usage)
testPermission (string $context, CommandSender $target, ?string $permission=null)
testPermissionSilent (CommandSender $target, ?string $permission=null)
Static Public Member Functions
static broadcastCommandMessage (CommandSender $source, Translatable|string $message, bool $sendToSource=true)
Public Attributes
const MAX_COORD = 30000000
const MIN_COORD = -30000000
Protected Member Functions
fetchPermittedPlayerTarget (string $testPermissionContext, CommandSender $sender, ?string $target, string $selfPermission, string $otherPermission)
getBoundedInt (CommandSender $sender, string $input, int $min, int $max)
getDouble (CommandSender $sender, string $value, float $min=self::MIN_COORD, float $max=self::MAX_COORD)
getInteger (CommandSender $sender, string $value, int $min=self::MIN_COORD, int $max=self::MAX_COORD)
getRelativeDouble (float $original, CommandSender $sender, string $input, float $min=self::MIN_COORD, float $max=self::MAX_COORD)
Detailed Description
Definition at line 35 of file VanillaCommand.php.
Member Function Documentation
broadcastCommandMessage()
static pocketmine\command\Command::broadcastCommandMessage (CommandSender $source, Translatable|string $message, bool $sendToSource = true) static inherited
Definition at line 175 of file Command.php.
execute()
pocketmine\command\Command::execute (CommandSender $sender, string $commandLabel, array $args) abstract inherited
Parameters
string[] $args @phpstan-param list<string> $args
Returns
mixed
Exceptions
CommandException
Reimplemented in pocketmine\command\ClosureCommand, pocketmine\command\defaults\BanCommand, pocketmine\command\defaults\BanIpCommand, pocketmine\command\defaults\BanListCommand, pocketmine\command\defaults\ClearCommand, pocketmine\command\defaults\CommandAliasCommand, pocketmine\command\defaults\DefaultGamemodeCommand, pocketmine\command\defaults\DeopCommand, pocketmine\command\defaults\DifficultyCommand, pocketmine\command\defaults\DumpMemoryCommand, pocketmine\command\defaults\EffectCommand, pocketmine\command\defaults\EnchantCommand, pocketmine\command\defaults\GamemodeCommand, pocketmine\command\defaults\GarbageCollectorCommand, pocketmine\command\defaults\GiveCommand, pocketmine\command\defaults\HelpCommand, pocketmine\command\defaults\KickCommand, pocketmine\command\defaults\KillCommand, pocketmine\command\defaults\ListCommand, pocketmine\command\defaults\MeCommand, pocketmine\command\defaults\OpCommand, pocketmine\command\defaults\PardonCommand, pocketmine\command\defaults\PardonIpCommand, pocketmine\command\defaults\ParticleCommand, pocketmine\command\defaults\PluginsCommand, pocketmine\command\defaults\SaveCommand, pocketmine\command\defaults\SaveOffCommand, pocketmine\command\defaults\SaveOnCommand, pocketmine\command\defaults\SayCommand, pocketmine\command\defaults\SeedCommand, pocketmine\command\defaults\SetWorldSpawnCommand, pocketmine\command\defaults\SpawnpointCommand, pocketmine\command\defaults\StatusCommand, pocketmine\command\defaults\StopCommand, pocketmine\command\defaults\TeleportCommand, pocketmine\command\defaults\TellCommand, pocketmine\command\defaults\TimeCommand, pocketmine\command\defaults\TimingsCommand, pocketmine\command\defaults\TitleCommand, pocketmine\command\defaults\TransferServerCommand, pocketmine\command\defaults\VersionCommand, pocketmine\command\defaults\WhitelistCommand, pocketmine\command\defaults\XpCommand, pocketmine\command\FormattedCommandAlias, and pocketmine\command\PluginCommand.
fetchPermittedPlayerTarget()
pocketmine\command\defaults\VanillaCommand::fetchPermittedPlayerTarget (string $testPermissionContext, CommandSender $sender, ?string $target, string $selfPermission, string $otherPermission) protected
Definition at line 39 of file VanillaCommand.php.
getBoundedInt()
pocketmine\command\defaults\VanillaCommand::getBoundedInt (CommandSender $sender, string $input, int $min, int $max) protected
Definition at line 105 of file VanillaCommand.php.
getDescription()
pocketmine\command\Command::getDescription () inherited
Definition at line 155 of file Command.php.
getDouble()
pocketmine\command\defaults\VanillaCommand::getDouble (CommandSender $sender, string $value, float $min = self::MIN_COORD, float $max = self::MAX_COORD) protected
Definition at line 93 of file VanillaCommand.php.
getId()
pocketmine\command\Command::getId () final inherited
Returns the globally unique ID for the command. This typically looks like namespace:name
Definition at line 92 of file Command.php.
Referenced by pocketmine\command\defaults\CommandAliasCommand\execute().
getInteger()
pocketmine\command\defaults\VanillaCommand::getInteger (CommandSender $sender, string $value, int $min = self::MIN_COORD, int $max = self::MAX_COORD) protected
Definition at line 71 of file VanillaCommand.php.
getName()
pocketmine\command\Command::getName () final inherited
Returns the local identifier of the command (without namespace or leading slash). This cannot be changed after creation.
Definition at line 85 of file Command.php.
getNamespace()
pocketmine\command\Command::getNamespace () final inherited
Definition at line 77 of file Command.php.
getPermissionMessage()
pocketmine\command\Command::getPermissionMessage () inherited
Definition at line 151 of file Command.php.
getPermissions()
pocketmine\command\Command::getPermissions () inherited
Returns
string[]
Definition at line 99 of file Command.php.
getRelativeDouble()
pocketmine\command\defaults\VanillaCommand::getRelativeDouble (float $original, CommandSender $sender, string $input, float $min = self::MIN_COORD, float $max = self::MAX_COORD) protected
Definition at line 83 of file VanillaCommand.php.
getUsage()
pocketmine\command\Command::getUsage () inherited
Definition at line 159 of file Command.php.
setDescription()
pocketmine\command\Command::setDescription (Translatable|string $description) inherited
Definition at line 163 of file Command.php.
setPermission()
pocketmine\command\Command::setPermission (?string $permission) inherited
Definition at line 116 of file Command.php.
setPermissionMessage()
pocketmine\command\Command::setPermissionMessage (Translatable|string $permissionMessage) inherited
Definition at line 167 of file Command.php.
setPermissions()
pocketmine\command\Command::setPermissions (array $permissions) inherited
Parameters
string[] $permissions
Definition at line 106 of file Command.php.
Referenced by pocketmine\command\ClosureCommand\__construct().
setUsage()
pocketmine\command\Command::setUsage (Translatable|string|null $usage) inherited
Definition at line 171 of file Command.php.
testPermission()
pocketmine\command\Command::testPermission (string $context, CommandSender $target, ?string $permission = null) inherited
Parameters
string $context usually the command name, but may include extra args if useful (e.g. for subcommands)
CommandSender $target the target to check the permission for
string | null $permission the permission to check, if null, will check if the target has any of the command's permissions
Definition at line 125 of file Command.php.
Referenced by pocketmine\command\defaults\CommandAliasCommand\execute(), pocketmine\command\defaults\TimeCommand\execute(), and pocketmine\command\defaults\WhitelistCommand\execute().
testPermissionSilent()
pocketmine\command\Command::testPermissionSilent (CommandSender $target, ?string $permission = null) inherited
Definition at line 140 of file Command.php.
Member Data Documentation
MAX_COORD
const pocketmine\command\defaults\VanillaCommand::MAX_COORD = 30000000
Definition at line 36 of file VanillaCommand.php.
MIN_COORD
const pocketmine\command\defaults\VanillaCommand::MIN_COORD = -30000000
Definition at line 37 of file VanillaCommand.php.
The documentation for this class was generated from the following file:
VanillaCommand.php